- id: mh_style
  name: MISS_HIT Style
  description: format all matlab files with MISS_HIT Style (https://misshit.org/tools.html)
  stages: [pre-commit]
  files: \.m$
  language: python
  entry: mh_style --fix
